src/Entity/Version.php
<?php

namespace App\Entity;

use App\Repository\VersionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VersionRepository::class)
 */
class Version
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modification_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_validated;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="versions")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $contributor;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $validator;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="versions")
     * @ORM\JoinColumn(nullable=false, onDelete="CASCADE")
     */
    private $article;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getModificationDate(): ?\DateTimeInterface
    {
        return $this->modification_date;
    }

    public function setModificationDate(?\DateTimeInterface $modification_date): self
    {
        $this->modification_date = $modification_date;

        return $this;
    }

    public function getIsValidated(): ?bool
    {
        return $this->is_validated;
    }

    public function setIsValidated(bool $is_validated): self
    {
        $this->is_validated = $is_validated;

        return $this;
    }

    public function getContributor(): ?User
    {
        return $this->contributor;
    }

    public function setContributor(?User $contributor): self
    {
        $this->contributor = $contributor;

        return $this;
    }

    public function getValidator(): ?User
    {
        return $this->validator;
    }

    public function setValidator(?User $validator): self
    {
        $this->validator = $validator;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use App\Entity\Tag;
use App\Entity\Version;

use App\Repository\VersionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use FOS\CKEditorBundle\Form\Type\CKEditorType;

use Vich\UploaderBundle\Form\Type\VichImageType;

class ArticleType extends AbstractType
{

    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $article = $options['data'];

        $versionRepository = $this->entityManager->getRepository(Version::class);
        $currentVersion = $article->getCurrentVersion();
        if($currentVersion){
            $version = $versionRepository->find($article->getCurrentVersion());
            $contentVersion = $version->getContent();
        } else {
            $contentVersion = '';
        }

        $builder
            ->add('title', TextType::class , ['label' => 'Nom'])
            ->add('description', TextareaType::class,['label' => 'Description'])
            ->add('monthly_article', null, ['label' => 'Article du mois'])
            ->add('content', CKEditorType::class,  ['mapped' => false, 'data' => $contentVersion , 'label' => 'Version en cours'])
            ->add('imageFile', VichImageType::class, [
                'required' => false, 
                'label' => 'Image',
                'download_uri' => false,
                'allow_delete' => false,
                ])
            ->add('tags', EntityType::class, [
                'class' => Tag::class, 
                'label' => 'Mots clés',
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => false,
                'by_reference' => false,
            ])
            ->add('categories', EntityType::class, [
                'class' => Category::class,
                'label' => 'Thèmes',
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => false,
                'by_reference' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Version;
use App\Form\ArticleType;
use App\Form\RechercheType;
use Symfony\Component\Mime\Email;
use App\Repository\ArticleRepository;
use App\Repository\VersionRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Knp\Component\Pager\PaginatorInterface; // Nous appelons le bundle KNP Paginator
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{

    /**
     * @Route("/", name="article_index", methods={"GET"})
     */

    public function index(Request $request, PaginatorInterface $paginator) // Nous ajoutons les paramètres requis
    {
        // Méthode findBy qui permet de récupérer les données avec des critères de filtre et de tri
        $donnees = $this->getDoctrine()->getRepository(Article::class)->findBy([], ['creation_date' => 'desc']);

        $articles = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            12 // Nombre de résultats par page
        );

        return $this->render('article/index.html.twig', [
            'articles' => $articles,
        ]);
    }


     /**
    * @Route("/recherche", name="search")
    */
    public function search(Request $request, ArticleRepository $articleRepository, PaginatorInterface $paginator)
    {
        $query = $request->query->get('search');

        if (!empty($query)) {
            $datas = $articleRepository->search($query);

            // Paginate the results of the query
            $articles = $paginator->paginate(
            // Doctrine Query, not results
            $datas,
            // Define the page parameter
            $request->query->getInt('page', 1),
            // Items per page
            10
            );

            return $this->render('article/search.html.twig', [
                'articles' => $articles,
            ]);
        }
        
        return $this->redirectToRoute('article_index');
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    public function new(Request $request, MailerInterface $mailer, ArticleRepository $articleRepository): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
            $entityManager = $this->getDoctrine()->getManager();
            $currentUser = $this->getUser();

            if($article->getMonthlyArticle()){
                $monthlyArticleOld = $articleRepository->findOneBy(['monthly_article' => true]);
                if($monthlyArticleOld){
                    $monthlyArticleOld->setMonthlyArticle(false);
                }
            }


            //On hydrate l'article des données manquantes
            $article->setCreator($currentUser)
            ->setIsPublished(false)
            ->setIsDeleted(false)
            ->setCreationDate(new \DateTime());

            //On créé une version (la première de l'article)
            $version = new Version();
            $version->setArticle($article);
            $version->setComment("Première version de l'article");

            //Récupére le contenu de l'input content et le met dans version.content
            $version->setContent($form->get('content')->getData());

            $version->setContributor($currentUser);
            $version->setIsValidated(false);
            $version->setModificationDate(new \DateTime());

            //Ajouter version aux versions et à current_version_id
            $article->addVersion($version);

            $entityManager->persist($article);
            $entityManager->persist($version);
            $entityManager->flush();

            $article->setCurrentVersion($version->getId());
            $article->setCreator($currentUser);
            $entityManager->persist($article);
            $entityManager->flush();

            $email = (new Email())
                ->from('from@example.com')
                ->to('to@example.com')
                ->subject('Un nouvel article vient d\'être publié !')
                ->html('<p>Un nouvel article vient d\'être publié sur le Wiki !</p>');

            $mailer->send($email);
            $this -> addFlash('success', "Votre article est créé. Il est en attente de validation.");

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/versions", name="article_versions",requirements={"id":"\d+"}, methods={"GET"})
     */
    public function showArticleVersions(Article $article, VersionRepository $versionRepository): Response
    {
        $allVersions = $versionRepository->findBy(['article' => $article->getId()], ['modification_date' => 'DESC']);
        return $this->render('article/versions.html.twig', [
            'article' => $article,
            'allVersions' => $allVersions
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", requirements={"id":"\d+"}, methods={"GET","POST"})
     * @IsGranted("ROLE_USER")
     */
    public function edit(Request $request, Article $article, MailerInterface $mailer, ArticleRepository $articleRepository): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //Si la case article du mois est cochée, on décoche la case de l'ancien article du mois s'il existe
            if($article->getMonthlyArticle()){
                $monthlyArticleOld = $articleRepository->findOneBy(['monthly_article' => true]);
                if($monthlyArticleOld){
                    $monthlyArticleOld->setMonthlyArticle(false);
                }
            }

            $currentUser = $this->getUser();
            $article->setCreator($currentUser)
            ->setCreationDate(new \DateTime());

            // créer une nouvelle version
            $version = new Version();
            $version->setContent($form->get('content')->getData())
            ->setModificationDate(new \DateTime())
            ->setIsValidated(false)
            ->setContributor($currentUser)
            ->setArticle($article);
            $this->getDoctrine()->getManager()->persist($version);
            $this->getDoctrine()->getManager()->flush();

            $article->addVersion($version);
            $article->setCurrentVersion($version->getId());

            $this->getDoctrine()->getManager()->flush();

            $email = (new Email())
                ->from('from@example.com')
                ->to('to@example.com')
                ->subject('Un article vient d\'être modifié !')
                ->html('<p>Un article vient d\'être modifié sur le Wiki !</p>');
            $mailer->send($email);

            $this -> addFlash('success', "Votre article a bien été modifié.");

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/{version_id?current}", name="article_show", requirements={"id":"\d+"}, methods={"GET"})
     */
    public function show(Article $article, VersionRepository $versionRepository, String $version_id): Response
    {
        if ($version_id == "current") {
            $version = $versionRepository->find($article->getCurrentVersion());
        } else {
            $version = $versionRepository->find($version_id);
        }

        // Fetch all versions for a given article
        $versions = $versionRepository->findBy(['article' => $article->getId()], ['modification_date' => 'DESC']);
        // Extract the three last versions, to display in the article page
        $lastVersions = array_slice($versions, 0, 3);

        // Fetch the contributor's id of each version and
        // keep only the ones different to the article's author
        $contributors = [];
        foreach ($versions as $vs) {
            if ($article->getCreator()->getId() != $vs->getContributor()->getId()) {
                $contributors[] = $vs->getContributor();
            }
        }

        //Remove duplicated entries
        foreach ($contributors as $k=>$v) {
            if (($kt=array_search($v, $contributors))!==false and $k!=$kt) {
                unset($contributors[$kt]);
            }
        }

        
        return $this->render('article/show.html.twig', [
            'article' => $article,
            'version' => $version,
            'lastVersions' => $lastVersions,
            'contributors' => $contributors,
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", requirements={"id":"\d+"}, methods={"DELETE"})
     * @IsGranted("ROLE_MODERATOR")
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete' . $article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cet article?');">
	<input type="hidden" name="_method" value="DELETE">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
	<button class="btn btn-danger">Supprimer</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-success">{{ button_label|default('Sauver') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Éditer l'article
{% endblock %}

{% block body %}

	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="{{ path('home') }}">Accueil</a>
		</li>
		<li class="breadcrumb-item">
			<a href="{{ path('article_index')}}">Articles</a>
		</li>
		<li class="breadcrumb-item active">Edition</li>
	</ol>

	<h1>Édition de l'article :</h1>


{{ include('article/_form.html.twig', {'button_label': 'Sauver'}) }}


	{{ include('article/_delete_form.html.twig') }}
	<div class="pb-4 pt-4">
		<a href="{{ path('article_index') }}">
			<i class="fas fa-arrow-circle-left mr-2"></i>Retour</a>
	</div>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous les articles
{% endblock %}

{% block body %}
<!-- Page Heading/Breadcrumbs-->
<ol class="breadcrumb">
	<li class="breadcrumb-item">
		<a href="{{ path('home') }}">Accueil</a>
	</li>
	<li class="breadcrumb-item active">Articles</li>
</ol>

<h1 class="mt-4 mb-3">
	Tous les articles
</h1>
<div class="row">
	{% for article in articles %}
	<div class="col-lg-4 col-sm-6 mb-4">
		<div class="card h-100">
			<a href="{{ path('article_show', {'id': article.id}) }}">
				<img class="card-img-top" src="{{ vich_uploader_asset(article, 'imageFile') }}" width="50px" />
			</a>
			<div class="card-body pb-5">
				<h4 class="card-title">
					<a href="{{ path('article_show', {'id': article.id}) }}">{{ article.title|capitalize }}</a>
				</h4>
				<small>{{article.getCreator.firstname}}
					{{article.getCreator.lastname}}</small>
				{% for category in article.categories %}
				<a href="{{ path('category_show', {'category': category.id}) }}"
					class="badge badge-info">{{category.name}}</a>
				{% endfor %}
				{% for tag in article.tags %}
				<a href="{{ path('tag_show', {'tag': tag.id}) }}" class="badge badge-dark">{{tag.name}}</a>
				{% endfor %}
				<p class="card-text pb-3 pt-3">{{ article.description|slice(0,100) }}</p>
				{% if app.user %}
				<a class="btn btn-warning position-absolute btn-sm" style="bottom: 20px;left: 20px;"
					href="{{ path('article_edit', {'id': article.id}) }}">Modifier</a>
				{% endif %}
				<a class="btn btn-primary position-absolute btn-sm" style="bottom: 20px;right: 20px;"
					href="{{ path('article_show', {'id': article.id}) }}">Lire la suite...</a>
			</div>
		</div>
	</div>
	{% else %}
	<div>
		<h2>Il n'y a pas d'article</td>
	</div>
	{% endfor %}
</div>

<!-- Pagination-->
<ul class="pagination justify-content-center">
	{{ knp_pagination_render(articles) }}
</ul>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel article
{% endblock %}

{% block body %}
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="{{ path('home') }}">Accueil</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{{ path('article_index')}}">Articles</a>
    </li>
    <li class="breadcrumb-item active">Création</li>
</ol>


	<h1>Création d'un article</h1>

	{{ include('article/_form.html.twig') }}

    <div class="pb-4 pt-4">
    <a href="{{ path('article_index') }}"><i class="fas fa-arrow-circle-left mr-2"></i>Retour</a>
    </div>

{% endblock %}

templates/article/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Resultat de recherche
{% endblock %}

{% block body %}
	<!-- Page Heading/Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="{{ path('home') }}">Accueil</a>
		</li>
		<li class="breadcrumb-item active">Articles</li>
	</ol>

	
	<div class="row">
	{% for article in articles %}
	<div class="col-lg-4 col-sm-6 mb-4">
		<div class="card h-100">
			<a href="{{ path('article_show', {'id': article.id}) }}">
				<img class="card-img-top" src="{{ vich_uploader_asset(article, 'imageFile') }}" width="50px" />
			</a>
			<div class="card-body pb-5">
				<h4 class="card-title">
					<a href="{{ path('article_show', {'id': article.id}) }}">{{ article.title|capitalize }}</a>
				</h4>
				<small>{{article.getCreator.firstname}}
					{{article.getCreator.lastname}}</small>
				{% for category in article.categories %}
				<a href="{{ path('category_show', {'category': category.id}) }}"
					class="badge badge-info">{{category.name}}</a>
				{% endfor %}
				{% for tag in article.tags %}
				<a href="{{ path('tag_show', {'tag': tag.id}) }}" class="badge badge-dark">{{tag.name}}</a>
				{% endfor %}
				<p class="card-text pb-3 pt-3">{{ article.description|slice(0,100) }}</p>
				{% if app.user %}
				<a class="btn btn-warning position-absolute btn-sm" style="bottom: 20px;left: 20px;"
					href="{{ path('article_edit', {'id': article.id}) }}">Modifier</a>
				{% endif %}
				<a class="btn btn-primary position-absolute btn-sm" style="bottom: 20px;right: 20px;"
					href="{{ path('article_show', {'id': article.id}) }}">Lire la suite...</a>
			</div>
		</div>
	</div>
	{% else %}
	<div>
		<h2>Aucun article ne correspond à votre recherche </h2>
	</div>
	{% endfor %}
	</div>

	<!-- Pagination-->
	<ul class="pagination justify-content-center">
		{{ knp_pagination_render(articles) }}
	</ul>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{article.title}}{% endblock %}

{% block body %}

	<!-- Page Heading/Breadcrumbs-->
	<ol class="breadcrumb mb-4">
		<li class="breadcrumb-item">
			<a href="{{ path('home') }}">Accueil</a>
		</li>
		<li class="breadcrumb-item">
			<a href="{{ path('article_index') }}">Articles</a>
		</li>
		<li class="breadcrumb-item active">{{article.title}}</li>
	</ol>
	<!-- Article Content-->
	<div class="row">
		{% if article.image %}
			<div class="col-md-6"><img class="img-fluid" src="{{ vich_uploader_asset(article, 'imageFile') }}" alt="{{article.image}}"/></div>
			<div class="col-md-6">
		{% else %}
			<div class="col-md-12">
		{% endif %}
					{% if version.isValidated %}
					<span class="badge badge-success">Article validé</span>
					{% else %}
					<span class="badge badge-warning">Article en cours de validation</span>
					{% endif %}
				<div class="d-flex mt-2">
					<h3>{{article.title}}</h3>
				</div>

				<div>
				<small class="text-muted">{{version.modificationDate|date('d-m-Y') }}
					-
					{{article.getCreator.firstname}}
					{{article.getCreator.lastname}}</small>
				</div>

				{# CONTRIBUTORS #}
				<div>
					<small class="text-muted">
					{% if contributors|length < 4 %}
					Contributeurs :
						{% for contributor in contributors %}
							{{contributor.firstname}}
							{{contributor.lastname}}.
						{% endfor %}
					{% else %}
						<button class="text-muted" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Contributeurs
						</button>
						<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
							{% for contributor in contributors %}
								<a class="dropdown-item" href="">{{contributor.firstname}} {{contributor.lastname}}</a>
							{% endfor %}
						</div>
					{% endif %}
					</small>
				</div>
				{# /CONTRIBUTORS #}

				{% for category in article.categories %}
					<a href="{{ path('category_show', {'category': category.id}) }}" class="badge badge-info">{{category.name}}</a>
				{% endfor %}
				{% for tag in article.tags %}
					<a href="{{ path('tag_show', {'tag': tag.id}) }}" class="badge badge-dark">{{tag.name}}</a>
				{% endfor %}

				<p class="pt-2">{{ article.description }}</p>
				<div>
					<ul class="list-unstyled">
						<u>Dernières versions</u>:
						{% for lastVersion in lastVersions %}
							<li>-
								<a href="{{ path('article_show', {'id': article.id, 'version_id': lastVersion.id}) }}">
									{{lastVersion.modificationDate|date('d-m-Y - H:i')}}
								</a>
								{% if article.currentVersion == lastVersion.id %}
									<span class="small">(Version actuelle publiée).</span>
								{% endif %}
							</li>

						{% endfor %}
					</ul>
					<a href="{{ path('article_versions', {'id': article.id}) }}" class="btn btn-outline-primary btn-sm">Toutes les versions</a>
					{% if article.currentVersion != version.id and is_granted('ROLE_MODERATOR')%}
						<a href="{{ path('version_publish', {'id': version.id}) }}" class="btn btn-primary">Publier cette version</a>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="mt-5">{{version.content|raw}}</div>
		{% if app.user %}
			<a class="btn btn-outline-warning" href="{{ path('article_edit', {'id': article.id}) }}">Modifier l'article</a>
		{% endif %}
	</div>

{% endblock %}

templates/article/validate_articles.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles en attente de validation
{% endblock %}

{% block body %}
	<!-- Page Heading/Breadcrumbs-->
	<ol class="breadcrumb">
		<li class="breadcrumb-item">
			<a href="{{ path('home') }}">Accueil</a>
		</li>
		<li class="breadcrumb-item active">Articles en attente de validation</li>
	</ol>
	
	<h1 class="mt-4 mb-3">
		Tous les articles en attente de validation
	</h1>
	<div class="row">
		{% for currentVersion in currentVersions %}
			<div class="col-lg-4 col-sm-6 mb-4">
				<div class="card h-100">
					<a href="{{ path('article_show', {'id': currentVersion.article.id}) }}"><img class="card-img-top" src="{{ vich_uploader_asset(currentVersion.article, 'imageFile') }}" width="50px" alt=" "/></a>
					<div class="card-body pb-5">
						<h4 class="card-title">
							<a href="{{ path('article_show', {'id': currentVersion.article.id}) }}">{{ currentVersion.article.title|capitalize }}</a>
						</h4>
						<small>{{currentVersion.article.getCreator.firstname}}
						{{currentVersion.article.getCreator.lastname}}</small>
						{% for category in currentVersion.article.categories %}
							<a href="{{ path('category_show', {'category': category.id}) }}" class="badge badge-info">{{category.name}}</a>
						{% endfor %}
						{% for tag in currentVersion.article.tags %}
							<a href="{{ path('tag_show', {'tag': tag.id}) }}" class="badge badge-dark">{{tag.name}}</a>
						{% endfor %}
						<p class="card-text pb-3 pt-3">{{ currentVersion.article.description|slice(0,100) }}</p>
						
                        <a class="btn btn-success position-absolute" style="bottom: 20px;" href="{{ path('version_validation', {'id': currentVersion.id}) }}">Valider l'article</a>
						<a class="btn btn-primary position-absolute" style="bottom: 20px;right: 20px;" href="{{ path('article_show', {'id': currentVersion.article.id}) }}">Lire la suite...</a>
					</div>
				</div>
			</div>
		{% else %}
			<div>
				<h2>Il n'y a pas d'article en attente de validation</td>
			</div>
		{% endfor %}
	</div>

	<!-- Pagination-->
	<ul class="pagination justify-content-center">
		{{ knp_pagination_render(currentVersions) }}
	</ul>
{% endblock %}

templates/article/versions.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{article.title}}
{% endblock %}

{% block body %}
	<!-- Page Heading/Breadcrumbs-->
	<ol class="breadcrumb mb-4">
		<li class="breadcrumb-item">
			<a href="{{ path('home') }}">Accueil</a>
		</li>
		<li class="breadcrumb-item">
			<a href="{{ path('article_index') }}">Articles</a>
		</li>
		<li class="breadcrumb-item active">{{article.title}}</li>
	</li>
	<li class="breadcrumb-item active">Toutes les versions</li>
</ol>
<h1>{{article.title}}</h1>
<div>
	<ul class="list-unstyled">
		<u>Toutes les versions</u>:
		{% for version in allVersions %}

			<li>
				<span class="small">Date de modification:</span>
				<a href="{{ path('article_show', {'id': article.id, 'version_id': version.id}) }}">{{version.modificationDate|date('d-m-Y H:i')}}
				</a>
				{% if article.currentVersion == version.id %}
					<span class="small">(Version actuelle publiée).</span>
				{% else %}
				{% if is_granted('ROLE_MODERATOR') %}
				{% include 'version/_delete_form.html.twig' %}
				{% endif %}
				{% endif %}
			</li>
		{% endfor %}
	</ul>

</div>{% endblock %}